services:
  # Frontend IPTV Renewal
  iptv-renewal-frontend:
    image: nginx:alpine
    container_name: iptv_renewal_frontend
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "5000:80"
    restart: unless-stopped
    networks:
      - shared_network

networks:
  shared_network:
    external: true  # Usa a rede compartilhada jรก existente
